= Digital Curricula Project

This is a project of Advance-IT Minnesota, a Center of Excellence of the Minnesota State University (formerly MNSCU) system. 

== Background of this document
The Minnesota State Colleges and Universities system is the 6th-largest educational system in the United States, with an annual budget approaching $2 billion. It represents http://www.mnscu.edu/colleges/campuses.html[31 institutions based on 54 campuses], from Winona State in the southeast to Thief River Falls in the northwest.  

At the http://advanceitmn.org/conference-recap-2016-new-directions-in-it-education/[2016 New Directions in IT conference], a faculty https://github.com/MN-ASG/digi-curr/wiki/Participants[working group] convened to consider the impacts of current technological trends on IT education. 

In particular, working group members are aware of and interested in the following topics:

* Agile software development
* Lean IT
* Cloud and web-scale IT
* DevOps
* Digital transformation

There is increasing evidence that these topics are significant to employers, and call for some educational response. This document examines these trends in light of current curricula, and makes recommendations in terms of learning objectives, current courses, and programmatic initiatives. 

The following are excerpts from the project proposal:

The outcome of this project is to improve the MNSCU IS/IT program service to the Minnesota workforce through developing instructional content (with faculty support) that better supports current industry needs. These under-served areas include:

* Digital transformation and digital product management 
* Agile software development, especially at organizational scale
* Integrated, practical “full stack” experiential learning
* End-to-end pipeline experience, including continuous integration and delivery (aka “DevOps”)
* Modern systems administration tools and techniques, particularly “infrastructure as code”
* Importance of cultural and organizational factors for high-performing Agile organizations 

These outcomes will in turn promote greater workforce readiness and career acceleration for graduating MNSCU students. 

The approach is to develop useful open-source material freely available to faculty, while supporting its use through defining reference curricula and developing seminar material to orient faculty to the new workforce demands. 
There are four components to this activity: 

1.	Survey and focus group research into current faculty views and understandings of Agile and workforce transformation.  Industry survey planned for MHTA; faculty survey for New Directions conference.
2.	A reference curriculum, with mappings to typical current curricula and their learning objectives, and attention to transition/bridging problems
3.	Initial conceptual vision for associated hands-on labs covering both “full stack” and “end to end pipeline” complexity.
4.	A 3-hour seminar to educate faculty on current industry trends (in particular, digital, Agile, DevOps, and related topics)

Reference curriculum details: 
Develop a reference/model curriculum covering the following high-level learning objectives (suggested):

* Theory and practice of Agile methods, including their extensions into digital product management and operations (“DevOps”)
* Test-driven development
* Scrum, Kanban, SAFe, and related methods
* The question of project vs. product management
* Techniques for scaling Agile
* Cultural and organizational factors
* Cloud and web-scale IT based on virtualization and open source 

Laboratory:
Objective: Support curriculum with common experience-based lab platform 

* Useful, realistic commercial application with appropriate architecture, including persistence, caching, front end, web and mobile delivery
* Virtual servers and composable, auto-scaling infrastructure defined per current practices as code (e.g. Chef recipes or Puppet manifests detailing nodes, software, configurations) and executable on institutional or Cloud infrastructure.
* Version-control-based workflow
* Load simulation and performance analytics (Cloud- and Web-scale computing demonstration)

These potentially to be supported with a common, flexible platform to be built with current open source technologies, defined though modern “infrastructure as code” techniques. No fee-based licenses or hardware to be required; the collateral will be open source, downloadable and operable by instructors and assistants with appropriate skills, given suitably powered computing infrastructure (either institutional or Cloud-based). 

Minimal goal: Vision and requirements. Stretch goal: Implementation.

An advisory board drawn from Agile thought leaders, industry, and academia is suggested.

_Note: The primary development vehicle for the collaborative work is the https://github.com/MN-ASG/digi-curr/wiki[wiki]._
